config/routes.rb
Rails.application.routes.draw do
# Guru::Application.routes.draw do

  concern :csv_exportable do
    get :export, on: :collection, :constraints => { format: :csv }
  end

  devise_for :users, skip: [:registrations], path: '', path_names: { sign_in: 'login', sign_out: 'logout' }

  authenticated :user do
    root to: 'dashboard#index'
  end

  namespace :dashboard do
    get :index, to: 'dasboard#index'
    get :visits, to: 'dasboard#visits', constraints: { format: :json }
    get :sources, to: 'dasboard#sources', constraints: { format: :json }
  end

  namespace :members, as: 'member' do
    resource :import, only: [:new, :create], as: 'import'
  end

  resources :members do
    concerns :csv_exportable

    delete :destroy_multiple, on: :collection
    get :active, on: :collection
    get :inactive, on: :collection

    resources :notes, except: [:show, :index], module: 'members'
    resource :account, except: [:show, :destroy]

    resources :payments, except: [:show, :edit, :update] do
      concerns :csv_exportable
    end

    resources :visits, except: :show do
      concerns :csv_exportable
    end
  end

  resources :classes, except: :show, concerns: :csv_exportable
  resources :levels, except: :show, concerns: :csv_exportable
  resources :sources, except: :show, concerns: :csv_exportable

  namespace :settings do
    resource :studio, only: [:edit, :update]
    resource :members, only: [:edit, :update], as: 'member'
    resources :users, except: [:show]
  end

  namespace :reports do
    namespace :members do
      resources :birthdays, only: [:index] do
        collection do
          get '/(:month)', to: 'birthdays#index'
          get '/(:month)/export', to: 'birthdays#export', :constraints => { format: :csv }
        end
      end
      resources :recent, only: [:index] do
        collection do
          get '/', to: 'recent#index'
          get :export, to: 'recent#export', constraints: { format: :csv }
        end
      end
      # namespace :birthdays do
      #   get '/(:month)/export', to: 'birthdays#export', :constraints => { format: :csv }
      #   get '/(:month)', to: 'birthdays#index'
      # end
      # namespace :recent do
      #   get :export, to: 'reports/members/recent#export'
      #   get '/', to: 'reports/members/recent#index'
      # end
    end

    namespace :attendance do
      get '/(:month)/(:year)/export', to: 'attendance#export', :constraints => { format: :csv }
      get '/(:month)/(:year)', to: 'reports/attendance/recent#index'
    end

    # namespace :accounts do
    #   get :export, to: 'accounts#export', constraints: { format: :csv }
    #   get '/(:type)', to: 'accounts#index'
    # end
    # namespace :payments do
    #   get '/(:month)/(:year)/export', to: 'payments#export', :constraints => { format: :csv }
    #   get '/(:month)/(:year)', to: 'payments#index'
    # end
    resources :accounts, only: [:index] do
      collection do
        get '/(:type)', to: 'accounts#index'
        get :export, to: 'accounts#export', constraints: { format: :csv }
      end
    end

    resources :payments, only: [:index] do
      collection do
        get '/(:month)/(:year)', to: 'payments#index'
        get '/(:month)/(:year)/export', to: 'payments#export', constraints: { format: :csv }, as: 'reports_payments_export'
      end
    end

  end

  # devise_for :user do
  #   root to: 'devise/sessions#new'
  # end
  #
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

end

app/models/visit.rb
class Visit < ActiveRecord::Base
  validates_date :visit_date

  belongs_to :klass, inverse_of: :visits
  belongs_to :member

  def self.recent(since = 15.days.ago)
    where('visit_date > ?', since)
  end
end

app/models/visit/csv_export.rb
class Visit::CsvExport
  def initialize(member)
    @member = member
  end

  def filename
    "#{@member.name}_visits.csv"
  end

  def to_csv
    CSV.generate do |csv|
      csv << %w(Visit\ Date Class Time)
      @member.visits.each do |visit|
        unless visit.klass.nil?
          csv << [visit.visit_date.strftime('%m/%d/%Y'), visit.klass.name, visit.klass.class_time.in_time_zone.strftime('%-l:%M %p')]
        end
      end
    end
  end
end

app/controllers/reports/visits_controller.rb
module Reports
  class VisitsController < ApplicationController
    include ::CsvExportable
    before_action :report

    def index
      @members = @report.members_visits.page params[:page]
    end
    
    def export
      export_csv @report
    end

    private

    def report
      @report = Report::VisitReport.new(current_studio, params[:month], params[:year])
    end
  end
end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController
  include MemberRequired
  include CsvExportable
  before_action :member
  before_action :visit, only: [:edit, :update, :destroy]

  def index
    respond_to do |format|
      format.html
      format.json do
        visits = []
        @member.visits.each do |v|
          visits << { id: v.id, title: v.klass.name_and_time, start: v.visit_date.strftime('%Y-%m-%d'), end: v.visit_date.strftime('%Y-%m-%d'), url: edit_member_visit_path(@member, v) } unless v.klass.nil?
        end
        render json: visits
      end
    end
  end

  def export
    export_csv Visit::CsvExport.new(@member)
  end

  def new
    @visit = @member.visits.build
  end

  def create
    @visit = @member.visits.build(permitted_params)
    if @visit.save
      redirect_to member_visits_url(@member), flash: { success: 'Visit was successfully created.' }
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @visit.update_attributes(permitted_params)
      redirect_to member_visits_url(@member), flash: { success: 'Visit was successfully updated.' }
    else
      render :edit
    end
  end

  def destroy
    if @visit.destroy
      redirect_to member_visits_url(@member), flash: { success: 'Visit was successfully deleted.' }
    end
  end

  private

  def visit
    @visit = @member.visits.find(params[:id])
  end

  def permitted_params
    params.require(:visit).permit(:visit_date, :klass_id, :member_id)
  end
end

app/views/visits/_form.html.haml
= form_for [@member, @visit], html: { class: 'form-horizontal' } do |f|
  = render 'layouts/shared/errors', object: @visit
  .form-group
    = f.label :visit_date, 'Date', class: 'col-lg-2 col-sm-2 control-label'
    .col-lg-10
      .input-group
        %span.input-group-addon
          %i.fa.fa-calendar
        = f.text_field :visit_date, "placeholder data-mask" => "99/99/9999", "data-date-format" => "mm/dd/yyyy", class: 'form-control datepicker default-date-picker', value: l(@visit.visit_date || Date.current)
  .form-group
    = f.label :klass_id, 'Class', class: 'col-lg-2 col-sm-2 control-label'
    .col-lg-10
      .input-group
        = f.select :klass_id, grouped_options_for_select([['Today', current_studio.klasses.today.map {|k| [k.name_and_time, k.id] } ], ['All', current_studio.klasses.map {|k| [k.name_day_and_time, k.id] } ]])
  %br/
  = f.submit nil, class: 'btn btn-primary'
  - if action?('edit')
    = link_to 'Delete Visit', member_visit_path(@member, @visit), confirm: 'Are you sure?', method: 'delete', class: 'btn btn-danger'
  = link_to 'Cancel', member_visits_path(@member), class: 'btn'

app/views/visits/edit.html.haml
.row
  .col-lg-3
    = render 'members/nav'
  .col-lg-9
    .panel
      .panel-heading
        Edit Visit
      .panel-body
        = render 'form'

app/views/visits/index.html.haml
= content_for :js do
  = javascript_include_tag 'visits'
.row
  .col-lg-3
    = render 'members/nav'
  .col-lg-9
    .panel
      .panel-heading
        Attendance
      .panel-body
        #calendar.has-toolbar.fc
        %br/
        .pull-right
          = link_to export_member_visits_path @member do
            %i.fa.fa-cloud-download
            Download
        = link_to 'New Visit', new_member_visit_path(@member), class: 'btn btn-primary'

app/views/visits/new.html.haml
.row
  .col-lg-3
    = render 'members/nav'
  .col-lg-9
    .panel
      .panel-heading
        Add Visit
      .panel-body
        = render 'form'